In [ ]:
#Construcción del modelo: tensorFlow utiliza un
#modelo de gráficos, lo que significa que primero se
#define el modelo y luego se ejecutan. Para definir el
#modelo, se puede usar la API Keras, que proporciona
#un conjunto de bloques de construcción de alto
#nivel para construir el modelo.

import tensorflow as tf

model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Dense(128, activation="relu"),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10)
])

#Compilación del modelo: antes de que el modelo
#pueda ser entrenado, debe ser compilado. Esto
#implica la especificación de la función de pérdida
#(que mide qué tan bien el modelo está realizando
#durante el entrenamiento), el optimizador (que
#determina cómo el modelo se actualiza basado
#en la función de pérdida) y cualquier métrica para
#monitorear durante el entrenamiento y prueba.

model.compile(optimizer="adam",
loss=tf.keras.losses.
SparseCategoricalCrossentropy(from_logits=True),
metrics=["accuracy"])


#Entrenamiento del modelo: ahora se puede entrenar
#el modelo utilizando los datos de entrenamiento.
#El modelo aprenderá a asociar las imágenes y las
#etiquetas. Durante el entrenamiento, la precisión
#del modelo mejora.

model.fit(x_train, y_train, epochs=5)

#Evaluación del modelo: una vez que el modelo
#ha sido entrenado, se puede evaluar qué tan bien
#funciona utilizando los datos de prueba.

model.evaluate(x_test, y_test, verbose=2)

#Predicciones: ahora que el modelo está entrenado,
#se puede usar para hacer predicciones.

probability_model = tf.keras.Sequential([
model,
tf.keras.layers.Softmax()
])

predictions = probability_model.predict(x_test)


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


NameError: name 'x_train' is not defined

In [ ]:
# Importamos la biblioteca NumPy
import numpy as np

# 1. Creación de arrays
# Un array en NumPy se puede crear a partir de listas en Python
# Ejemplo de un array unidimensional
array = np.array([1, 2, 3])  # Esto crea un array con los elementos [1, 2, 3]
print("Array unidimensional:", array)

# 2. Operaciones matemáticas con arrays
# Las operaciones en NumPy son vectorizadas, lo que significa que se aplican a todo el array sin necesidad de bucles
result = array * 2  # Multiplica cada elemento del array por 2
print("Array multiplicado por 2:", result)

# 3. Creación de una matriz (array bidimensional)
# Una matriz se puede crear como un array de arrays
matrix = np.array([[1, 2], [3, 4], [5, 6]])  # Esto crea una matriz de 3 filas y 2 columnas
print("Matriz 3x2:\n", matrix)

# 4. Cambiar la forma de un array (reshape)
# NumPy permite reorganizar los datos de un array
reshaped = matrix.reshape(2, 3)  # Cambiamos la forma a 2 filas y 3 columnas
print("Matriz reconfigurada a 2x3:\n", reshaped)

# 5. Preprocesamiento de datos: Normalización
# Normalizar los datos implica escalar los valores para que tengan una media de 0 y una desviación estándar de 1
data = np.array([10, 20, 30])  # Datos originales
normalized = (data - np.mean(data)) / np.std(data)  # Normalización
print("Datos normalizados:", normalized)

# 6. Operaciones básicas de selección y filtrado
# Selección de elementos en un array
print("Elemento en la posición [1,1] de la matriz original:", matrix[1, 1])  # Accede al elemento en la fila 2, columna 2

# Filtrar elementos de un array
filtered = data[data > 15]  # Selecciona solo los elementos mayores a 15
print("Elementos mayores a 15:", filtered)

# 7. Interoperabilidad entre NumPy y TensorFlow
# Los arrays de NumPy pueden convertirse fácilmente en tensores de TensorFlow y viceversa (requiere la biblioteca TensorFlow)
import tensorflow as tf

# Convertir un array NumPy a un tensor TensorFlow
tensor = tf.convert_to_tensor(array, dtype=tf.float32)
print("Tensor TensorFlow convertido desde NumPy:", tensor)

# Convertir un tensor TensorFlow de vuelta a un array NumPy
array_from_tensor = tensor.numpy()
print("Array NumPy convertido desde TensorFlow:", array_from_tensor)


Array unidimensional: [1 2 3]
Array multiplicado por 2: [2 4 6]
Matriz 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Matriz reconfigurada a 2x3:
 [[1 2 3]
 [4 5 6]]
Datos normalizados: [-1.22474487  0.          1.22474487]
Elemento en la posición [1,1] de la matriz original: 4
Elementos mayores a 15: [20 30]
Tensor TensorFlow convertido desde NumPy: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Array NumPy convertido desde TensorFlow: [1. 2. 3.]


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

#PREPROCESAMIENTO DE KERAS

# -----------------
# 1. Preprocesamiento para imágenes
# -----------------

# Definir las dimensiones de las imágenes de entrada
image_height, image_width = 128, 128

# Crear un pipeline de preprocesamiento para las imágenes
# Este pipeline redimensiona las imágenes y normaliza los valores de los píxeles
image_preprocessing = tf.keras.Sequential([
    layers.Resizing(image_height, image_width),   # Cambia el tamaño de las imágenes a 128x128 píxeles
    layers.Rescaling(1./255)                     # Normaliza los valores de los píxeles al rango [0, 1]
])

# -----------------
# 2. Preprocesamiento para texto
# -----------------

# Configurar el número máximo de tokens (palabras únicas) y la longitud máxima de las secuencias
max_tokens = 10000  # Vocabulario máximo
output_sequence_length = 50  # Longitud máxima de las secuencias

# Crear una capa de vectorización para procesar texto
text_vectorization = layers.TextVectorization(
    max_tokens=max_tokens,                # Número máximo de palabras en el vocabulario
    output_sequence_length=output_sequence_length  # Longitud máxima de las secuencias de salida
)

# Adaptar la capa de vectorización a un conjunto de textos de muestra
# Esto crea un vocabulario basado en los datos de entrenamiento
sample_texts = ["Esta es una oración de ejemplo", "Otra oración para el vectorizador"]
text_vectorization.adapt(sample_texts)  # Aprende el vocabulario y asigna índices a las palabras

# -----------------
# 3. Modelo que Integra Ambos Flujos
# -----------------

# Crear la entrada para imágenes, especificando el tamaño esperado (128x128 píxeles con 3 canales para RGB)
image_input = layers.Input(shape=(128, 128, 3), name="image_input")

# Aplicar el pipeline de preprocesamiento a las imágenes
processed_image = image_preprocessing(image_input)

# Crear la entrada para texto, especificando que será una cadena de texto
text_input = layers.Input(shape=(1,), dtype=tf.string, name="text_input")

# Aplicar el vectorizador de texto a la entrada de texto
processed_text = text_vectorization(text_input)

# Agregar una capa de embedding para convertir las secuencias de texto en representaciones vectoriales densas
embedded_text = layers.Embedding(input_dim=max_tokens, output_dim=64)(processed_text)

# Reducir las dimensiones del tensor procesado por las imágenes utilizando una capa de pooling global
# Esta capa calcula el promedio global sobre todas las dimensiones espaciales (altura y ancho)
pool_image = layers.GlobalAveragePooling2D()(processed_image)

# Reducir las dimensiones del tensor procesado por el texto utilizando un pooling global sobre las secuencias
pool_text = layers.GlobalAveragePooling1D()(embedded_text)

# Combinar (concatenar) las salidas procesadas de imágenes y texto en un único tensor
combined = layers.Concatenate()([pool_image, pool_text])

# Añadir una capa densa (fully connected) para aprender patrones combinados entre texto e imágenes
dense_output = layers.Dense(64, activation="relu")(combined)

# Añadir una capa de salida final con una única neurona y una activación sigmoide (para clasificación binaria)
final_output = layers.Dense(1, activation="sigmoid", name="output")(dense_output)

# Construir el modelo final especificando las entradas y salidas
model = models.Model(inputs=[image_input, text_input], outputs=final_output)

# -----------------
# 4. Compilación y Entrenamiento
# -----------------

# Compilar el modelo especificando:
# - Optimizador (Adam) para ajustar los pesos
# - Función de pérdida (Binary Crossentropy) para clasificación binaria
# - Métrica de evaluación (Accuracy) para monitorear la precisión
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# -----------------
# 5. Datos Simulados
# -----------------

# Crear datos de ejemplo para imágenes (10 imágenes aleatorias de tamaño 128x128x3)
dummy_images = np.random.random((10, 128, 128, 3))

# Crear datos de ejemplo para textos (10 oraciones iguales)
dummy_texts = tf.constant(["Esta es una oración"] * 10, dtype=tf.string)

# Crear etiquetas aleatorias (0 o 1) para las 10 muestras
dummy_labels = np.random.randint(2, size=(10, 1))

# -----------------
# 6. Entrenamiento del Modelo
# -----------------

# Entrenar el modelo usando los datos simulados
# - `dummy_images` se pasan como entrada para las imágenes
# - `dummy_texts` se pasan como entrada para el texto
# - `dummy_labels` se usan como las etiquetas de entrenamiento
# - El modelo entrenará durante 5 épocas
history = model.fit(
    {"image_input": dummy_images, "text_input": dummy_texts},  # Entradas
    dummy_labels,  # Etiquetas
    epochs=5  # Número de épocas
)



Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3000 - loss: 0.6977
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7000 - loss: 0.6866
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7000 - loss: 0.6776
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7000 - loss: 0.6700
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7000 - loss: 0.6636


In [4]:
#TENSORFLOWS DATASETS

import tensorflow_datasets as tfds

# Cargar el conjunto de datos CIFAR-10
dataset, info = tfds.load('cifar10', split=['train', 'test'], as_supervised=True, with_info=True)

# Dividir en entrenamiento y prueba
train_dataset = dataset[0].shuffle(1000).batch(32).repeat()
test_dataset = dataset[1].batch(32)

# Mostrar información sobre los datos
print(info)


tfds.core.DatasetInfo(
    name='cifar10',
    full_name='cifar10/3.0.2',
    description="""
    The CIFAR-10 dataset consists of 60000 32x32 colour images in 10 classes, with 6000 images per class. There are 50000 training images and 10000 test images.
    """,
    homepage='https://www.cs.toronto.edu/~kriz/cifar.html',
    data_dir='/root/tensorflow_datasets/cifar10/3.0.2',
    file_format=tfrecord,
    download_size=Unknown size,
    dataset_size=132.40 MiB,
    features=FeaturesDict({
        'id': Text(shape=(), dtype=string),
        'image': Image(shape=(32, 32, 3), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=50000, num_shards=1>,
    },
    citation="""@TECHREPORT{Krizhevsky09learningmultiple,
        author = {Alex Krizhevsky},
        title = {Lear